### ISSUE TITLE
安装完成后根据文档上的用户名和密码登录不进去

### ISSUE THREAD

**Issue by zhangle-dev** [shikanon/kubeflow-manifests#26]
我按照步骤安装完成之后，访问30000端口到登录页面，用admin@example.com/password 登录一直失败，不知道为什么。
还有个问题，我之前通过官网的步骤安装过，好像没有登录页面，这个认证功能是哪个组件实现的，在哪里可以关掉。
希望能够解答，谢谢

**Comment by shikanon** [comment]
认证通过 patch 下的 auth.yaml 文件实现的：
```yaml
apiVersion: v1
data:
  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    - email: "admin@example.com"
      # hash string is "password"
      hash: "$2y$12$X.oNHMsIfRSq35eRfiTYV.dPIYlWyPDRRc1.JVp0f3c.YqqJNW4uK"
      # https://github.com/dexidp/dex/pull/1601/commits
      # FIXME: Use hashFromEnv instead
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/login/oidc"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
kind: ConfigMap
metadata:
  name: dex
  namespace: auth
---
apiVersion: v1
data:
  profile-name: kubeflow-user-example-com
  user: admin@example.com
kind: ConfigMap
metadata:
  name: default-install-config-9h2h2b6hbk
---
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: kubeflow-user-example-com
spec:
  owner:
    kind: User
    name: admin@example.com
```
@zhangle-dev 你可以delete 掉 auth 命名空间下的 dex 名字的pod，让他重启看看，有可能是配置没重载
