### ISSUE TITLE
pipline执行出现secret "mlpipeline-minio-artifact" not found 问题

### ISSUE THREAD

**Issue by LittleTear** [shikanon/kubeflow-manifests#98]
![微信图片_20220420101727](https://user-images.githubusercontent.com/45777286/164133676-fc0033b8-dc05-4d5b-bf2d-300cac39c964.png)

**Comment by LittleTear** [comment]
已在关闭的issues中找到

**Comment by LittleTear** [comment]
## secret "mlpipeline-minio-artifact" not found 问题
>解决办法
```
cd patch
kubectl delete -f pipeline-env-platform-agnostic-multi-user.yaml
kubectl apply -f pipeline-env-platform-agnostic-multi-user.yaml

cd manifest1.3
kubectl delete -f  017-pipeline-env-platform-agnostic-multi-user.yaml
kubectl apply -f  017-pipeline-env-platform-agnostic-multi-user.yaml
```

>之后重启pipline 会如下报错

## kubelet MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file

```
cd patch
vi  workflow-controller.yaml 

修改 containerRuntimeExecutor: k8sapi 为 containerRuntimeExecutor: pns

##################################
apiVersion: v1
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      endpoint: "minio-service.kubeflow:9000"
      bucket: "mlpipeline"
      keyFormat: "artifacts/{{workflow.name}}/{{pod.name}}"
      # insecure will disable TLS. Primarily used for minio installs not configured with TLS
      insecure: true
      accessKeySecret:
        name: mlpipeline-minio-artifact
        key: accesskey
      secretKeySecret:
        name: mlpipeline-minio-artifact
        key: secretkey
  containerRuntimeExecutor: pns
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: workflow-controller-configmap
  namespace: kubeflow

```
>删除重启
```
kubectl delete -f  workflow-controller.yaml 
kubectl apply -f  workflow-controller.yaml 
```
